version: "3"
services:
  
  client:
    build: ./client/
    ports: 
      - "3333:3333"
    volumes:
      - './client:/app'
    networks: 
      - net

  server:
    build: ./server/
    ports:
      - "5000:5000"
    volumes:
      - ./server:/code
    environment:
      FLASK_ENV: development
    networks:
      - net

  db:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    volumes:
        - ./mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: api
      MYSQL_USER: toor
      MYSQL_PASSWORD: toor
    networks:
      - net

  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminprojet
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    restart: always
    ports:
      - 2000:80
    volumes:
      - /sessions
    networks:
      - net

networks:
  net:
    driver: bridge

